# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Austin Wang
tagline:          Path to Web Application Development
url:              
paginate:         1
baseurl:          http://austin-sa-wang.github.io/
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
